### ISSUE TITLE
piwigo-modus with OpenStreetmap

### ISSUE THREAD

**Issue by prolibre** [Piwigo/piwigo-modus#41]
I don't know if the problem concerns the theme or the OpenStreetMap plugin but there is a display problem (some elements of the map go over the menu). It should be possible to fix this with an index.

![Piwigo_osm_bug](https://user-images.githubusercontent.com/17174902/106439511-0eacf080-6478-11eb-920f-5289a1cc631b.jpg)

**Comment by HWFord** [comment]
Fixed in OpenStreet Map plugin
