### ISSUE TITLE
Broken URL in skins CSS

### ISSUE THREAD

**Issue by codeceptsDE** [Piwigo/piwigo-modus#54]
All skins css files contain a broken url call `url(/themes/default/icon/infos.png)`.
For example:
https://github.com/Piwigo/piwigo-modus/blob/03b6b637df9961086386e0c189970bfc4e8eb0f3/skins/newspaper.css#L19-L22

It should be the relative url `url(../../themes/default/icon/infos.png`, similar (but not quite identical) to here:
https://github.com/Piwigo/piwigo-modus/blob/03b6b637df9961086386e0c189970bfc4e8eb0f3/css/base.css.tpl#L415-L421

Otherwise, this causes 404s if Piwigo is not at the root of the domain.

**Comment by davemosk** [comment]
I have this problem too...   I can't use the Modus theme until this is fixed :-(

**Comment by HWFord** [comment]
fixed in issue #72
