### ISSUE TITLE
Picture info box over-extends if filename long

### ISSUE THREAD

**Issue by roydenyates** [Piwigo/piwigo-modus#56]
Piwigo latest, Modus.

If the image filename is long, the image information display on the right extends below the lowermost image margin:

![Screenshot from 2023-05-11 18:52:51](https://github.com/Piwigo/piwigo-modus/assets/10870125/2f6cd5d6-ea89-431f-a553-f8eae03731f6)

**Comment by HWFord** [comment]
@roydenyates do you have anything else activated in your Piwigo ? I have tried to reproduce the problem but the title fits in the window. The file name automatically go to the next line.

![image](https://github.com/Piwigo/piwigo-modus/assets/54360213/8f9d18af-7ce2-468b-b281-a1c846d9576c)

**Comment by roydenyates** [comment]
I now have disabled all plug-ins and removed all added entries in localfiles editor, reloaded nginx etc, and still it looks as in the bug report.

Your test used hyphens whilst I had underscore - is that a meaningful difference?

I tried with Firefox and  Chrome.  At 100% mag it displays the issue, at 90% not because it fits.  At 150% it displays without extending the frame by truncating the file name.
