### ISSUE TITLE
Search with some template modes are a "quirks"

### ISSUE THREAD

**Issue by osworx** [Piwigo/piwigo-modus#63]
Using latest version of modus, at some template modes the output is not really formatted and works only with a few modes.

Clear:
![grafik](https://github.com/Piwigo/piwigo-modus/assets/1905204/065af3e1-218d-4048-af4a-d3559fa52beb)
Dark:
![grafik](https://github.com/Piwigo/piwigo-modus/assets/1905204/e84c6cbf-a57e-4865-bf79-310cfd2920df)
Same with:
Dark Lagoon, Dark Raddish, Dark Sky, Debug, Grey

Working only with:
Avocado, Blueberry, Cafe Latte, Clacier, Neon Orange, Neon Pink, Newspaper, Quartz, Splash, Strawberry Jam, Swimming Pool
As sample Glacier:
![grafik](https://github.com/Piwigo/piwigo-modus/assets/1905204/430ff432-09cb-4d79-840e-21e82241c913)

**Comment by HWFord** [comment]
This will be fixed when a new version of modus gets published. The new version will be compatible with Modus and its different skins. I am currently working on this
