### ISSUE TITLE
Modus Themes, Drop down display Issues

### ISSUE THREAD

**Issue by Michael-B-High** [Piwigo/piwigo-modus#75]
**Inconsistent or unreadable drop down menus on narrow displays.** 
Screen shots with my comments and notes may be viewed [here](https://piwigo14.thehighs.org/index.php?/category/41) .
### Issue common to the light themes
The _backgroundColor_ values have not been set in the _../skins/-Skin name-.inc.php_ files and remain at the default value of ‘#3f3f3f’. The change needed for the _neon_orange.inc.php_ file is as follows;-
```
	'dropdowns' => array(
			// REQUIRED - cannot be transparent
			'backgroundColor' => '#e8e8ea', 
		),
```
I suggest the following colours for the other affected skins;-
Avocado	#e1ffe1
Blueberry	#131e24
Cafe_latte	#f3f3f3
Debug		#2b4170
Neon_pink	#f3f3f3
Strawberry_jam	#fff5f5
Swimming_pool	#618f61 
### Issues common to all themes
The inconsistent margins, spacing and sometimes the colour of the icon for 'Search in this set' is common to all of the skins. The cause is to be found in the use of a 'gallery-icon' class rather than the 'pwg-icon' class used elsewhere. This can be fixed by amending lines 18 and 163 in the _../themes/default/template/index.tpl_ file as follows ;-
from : 	`gallery-icon-search-folder`
to : 	`pwg-icon-search-folder`
### Unresolved Issues
As the display improved, various errors or inconsistencies came to light, such as the error in the _../skins/strawberry_jam.css_ file shown in this [screen shot](https://piwigo14.thehighs.org/picture.php?/866/category/41). Resolving them would be a project in itself. I will raise this separately.
My suggestion is that these changes be considered as a quick fix to minor issues. They currently detract from modus in a way that reflects badly on Piwigo.

**Comment by HWFord** [comment]
Thank you for your input, I have fixed the dropdown color issues. please create sepereate issue for seperate items so they can also be fixed
